### ISSUE TITLE
Planning issue for next major release of LDI

### ISSUE THREAD

**Issue by jywarren** [publiclab/Leaflet.DistortableImage#126]
Coming out of the broader MapKnitter upgrade project, I'm collecting a set of issues/ideas/projects which we'd like to tackle in the next big release. 

## Projects

* [ ] multiple image selection #29, means to drag multiple or perform actions on image collections
* [ ] simpler menu API to add new tools (even after initialization, like `img = new L.DistortableImageOverlay(...); img.addAction();` perhaps? (#141)
* [ ] abstract tools UI from tools functions, allow for alternative tools UIs to be attached instead of default Toolbar (#140)
  * [ ] nested menus or modal for more tools, as the menu runs out of space? (also build on #140)
* [ ] image ordering? #84, mapknitter link-in in https://github.com/publiclab/mapknitter/issues/116
* [x] full res download from menu (https://github.com/publiclab/Leaflet.DistortableImage/pull/100 but needs a way to pass in full-res original image in options)
  * [ ] 'place with geodata' tool, not sure if this lives in MK or LDI, we have a lot of code for it here which could be broken out into a separate file, or even a separate npm module: https://github.com/publiclab/Leaflet.DistortableImage/issues/142

## Needs bug documentation

(need to list out all observed bugs with screenshots/gifs, could ask people to help with this in an issue?)

- [ ] debugging of menu placement, hide/show
- [ ] thorough cross-browser UI testing of toolbar
- [x] toolbar bugs when you delete images

## Compatibility

* [ ] compatibility with React wrapper: https://github.com/publiclab/Leaflet.DistortableImage/issues/105

Assorted other issues/bugs/ideas here: https://github.com/publiclab/Leaflet.DistortableImage/issues/87

* [x] resolve `grunt build` and `karma` issue in Travis CI: https://github.com/publiclab/Leaflet.DistortableImage/pull/122

## Assorted utility functions

* `average_scale`, `cm_per_pixel`, `average_cm_per_pixel` which we do in Ruby here, could be re-implemented in JS, following [Leaflet conventions](https://leafletjs.com/reference-1.4.0.html): https://github.com/publiclab/mapknitter/blob/main/app/models/map.rb#L123-L171

## Dream projects

* [ ] detect similar features in nearby or overlapping images while dragging: https://github.com/publiclab/Leaflet.DistortableImage/issues/110

**Comment by jywarren** [comment]
@gauravano @SidharthBansal  starting to build this out a good bit! These are pretty important to the overall project as they focus on the usability and debugging of the UI.

**Comment by rexagod** [comment]
Interesting!! I'd like to start working on issues here!

(@jywarren Regarding #122, I was thinking we could maybe try using something like `grunt-contrib-connect` on port `9876`, since there is no listener assigned to it right now?)

**Comment by jywarren** [comment]
@rexagod @sashadev-sky I've broken out a number of these into new stand-alone issues with some code links and discussion! Would love to hear your thoughts!

**Comment by sashadev-sky** [comment]
@jywarren I will take on 
"multiple image selection #29, means to drag multiple or perform actions on image collections" if that is okay!

**Comment by rexagod** [comment]
> * nested menus or modal for more tools, as the menu runs out of space? (also build on #140)

How about displaying a modal with keymaps for all the different functions, while including the more important ones in the toolbar, or even swapping the toolbar icons with the ones that user frequents?

**Comment by sashadev-sky** [comment]
I was thinking about that too! It could be one of the interfaces the developer can select for their sidebar. Also that would be cool to have it auto sort by how frequently they are used.
<img width="873" alt="screen shot 2019-02-20 at 4 46 24 pm" src="https://user-images.githubusercontent.com/41092741/53126871-1f842600-352f-11e9-8cce-ada463c39cef.png">

I thought this legends window I saw on an example map was very pleasant looking

**Comment by jywarren** [comment]
Oh cool! Yes, and i think i mention the alternative Control (not popup) UI for Leaflet.toolbar in https://github.com/publiclab/Leaflet.DistortableImage/issues/140, which could help achieve something like this too!

**Comment by rexagod** [comment]
@jywarren :arrow_up:  Please review these whenever you have the time to. I hope the barnraising event went well, the twitterverse was full of it! :bird: :+1:

**Comment by jywarren** [comment]
Aww, thanks @rexagod -- i was resting so i missed this! :laugh: Will do now!

**Comment by rexagod** [comment]
Pinging @jywarren to open this.
