### ISSUE TITLE
Add a `#replaceTool` method

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/Leaflet.DistortableImage#367]
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# Problem 

We already have methods `#addTool` `#removeTool` and `#hasTool` for `L.DistortableImage.Edit`:

https://github.com/publiclab/Leaflet.DistortableImage/blob/0a162b57aac8be4644a878901567f306c3c006ee/src/edit/DistortableImage.Edit.js#L211-L238

# Solution

We would like a `#replaceTool` method now. It should take in 2 tools, one gets removed, the other takes its place. You can use the other methods mentioned above for reference. 

**Part 1:**  -- **complete**

- [x] add a `#replaceTool` method
- [x] document it in the `README` (just follow the current documentation pattern - see other tool related methods documented for reference)
- [x] add a test for it - test that it adds the tool in the same index position as the old tool, not to the end of the array
- [x] bump the package 1 minor version "x" given "0.0.x" so we can pull the new version into our [MapKnitter](https://github.com/publiclab/mapknitter) repository, which uses this library for some of its core functionality, and use this function! (See part 2)

=== mentor will have to publish to NPM before proceeding to part 2 ===

**Part 2:** -- **open**

Use it downstream in MapKnitter:

MapKnitter takes advantage of LDI's tool API to remove the delete tool, create a custom variation of it, and add that tool instead.

https://github.com/publiclab/mapknitter/blob/5d825a9992dce58ae2d295612662d8402f65f5ee/app/assets/javascripts/mapknitter/Map.js#L160-L169

 After completing part 1, you will want to
- [ ] update the `Leaflet.DistortableImage` dependency version in MK's `package.json`. (Update it manually, run `yarn install`)
- [ ] navigate the installation issue by fixing the problem referenced here: https://github.com/publiclab/mapknitter/issues/1124
- [ ] replace out the code linked above with an implementation using `#replaceTool`

# Logistics

- Part 1 and 2 are considered separate tasks so you get points for each.
- Feel free to complete just part 1, and leave part 2 for someone else. - but you will get the bonus of seeing how LDI is already used in production on MK if you do both!

 This task is marked as `medium` because of the wide range of skills it touches on (code, testing, doc, refactoring, etc.).

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, if there's an additional checklist provided for getting it merged, get those boxes checked off. Either way, mention me @sashadev-sky for a review.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by sashadev-sky** [comment]
**Uploaded on GCI dashboard**

**Comment by SidharthBansal** [comment]
Published

**Comment by chen-robert** [comment]
I'm contributing as a part of GCI, would it be possible to assign this task to me please?

**Comment by sashadev-sky** [comment]
Pt2 Uploaded on GCI dashboard

**Comment by chen-robert** [comment]
@sashadev-sky regarding part 2, I noticed the behavior of `replaceTool` seems to be a bit different from what exists currently in mapknitter. 

https://github.com/publiclab/mapknitter/blob/5d825a9992dce58ae2d295612662d8402f65f5ee/app/assets/javascripts/mapknitter/Map.js#L162-L163

Currently `replaceTool` will only replace the tool if the original tool exists. It would thus behave as 

```javascript
if (edit.hasTool(Delete)) { 
      edit.removeTool(Delete); }
      edit.addTool(mapknitter.customDeleteAction());
}
```

Should I change the behavior of `replaceTool`? Or leave the original code as is and just update the package version?

**Comment by sashadev-sky** [comment]
@chen-robert i see your point. I guess it would be 
```
edit.hasTool(Delete) ? edit.replaceTool(Delete, mapknitter.customDeleteAction()) : edit.addTool(mapknitter.customDeleteAction())
```
and thats ok! Also note i needed to bump to 0.8.7 after merging your 0.8.6 because I forgot about the package-lock.json file. That needs to be included in the PR anytime package.json is changed! You just run `npm install` after updating package.json to update it too. So pull in 0.8.7 :)

**Comment by sashadev-sky** [comment]
also Pt2. is on the dashboard in draft mode but needs to be published by an admin. Hopefully will be published tonight and i'll make sure u can claim it if you haven't already claimed another one. Sorry for the inconvenience

**Comment by chen-robert** [comment]
No problem, I'll push the fix now and claim it once it gets uploaded

**Comment by sashadev-sky** [comment]
cool thank you!

**Comment by sashadev-sky** [comment]
@chen-robert oh also please note this issue just opened!! https://github.com/publiclab/mapknitter/issues/1124

Delete needs to be updated to `L.DeleteAction` as well since the naming convention has changed in a past PR and has not since been update there!

**Comment by chen-robert** [comment]
Okay, I'll take a look at it afterward! Not sure if I'm allowed to make a PR for it though, @SidharthBansal said to focus on the GCI tagged ones.
